### ISSUE TITLE
BertScorer breaks with latest current version of matplotlib 

### ISSUE THREAD

**Issue by mattshardlow** [Tiiiger/bert_score#120] opened 2021-12-17 11:54 UTC
If I try to do:

> from bert_score import Bert_Scorer

I get

> AttributeError: module 'matplotlib.cbook' has no attribute '_make_class_factory'

I can fix this by installing matpotlib 3.4.3, in which case the error goes.

This can be fixed by changing the req for matpotib to 3.4.3, but it may be better to change the bit that's relying on the old version of matplotlib code to avoid collision errors in larger packages using bert_score.

**Comment by Tiiiger** [comment] 2022-01-31 06:42
hi @mattshardlow 

sorry, forgot to reply earlier. I am on `matplotlib==3.5.1` and with the newest version of `bert_score`, I couldn't reproduce your error. 

I am guess this could be a version issue with your matplotlib installation? but glad to hear that you kind of fixed it by installing 3.4.3. 

Closing for now.

**Closed by Tiiiger** 2022-01-31 06:42 UTC
