### ISSUE TITLE
Is there a way to return the best sentence? Not just the score.

### ISSUE THREAD

**Issue by TanAidan** [Tiiiger/bert_score#101] opened 2021-06-10 19:23 UTC
If I have multiple candidates and 1 reference and I want to find the best candidate (evaluating on semantic similarity) Is there a way to use the Bert Scorer to score all the candidates at once without multiple score calls. Also is there a way to return the best sentence that is associated with the outputted best score? 

Really cool project and thank you so much in advance!

**Comment by felixgwu** [comment] 2021-06-10 21:10
Duplicate of #98

**Comment by felixgwu** [comment] 2021-06-10 21:17
Hi @TanAidan,

Unfortunately, this is not supported with our API, but it is very similar to #98. You can follow the instruction there. However, there is a small difference that you want the best candidate, not the best reference.
The BERTScore-F is symmetric, so the score should be the same if you swap them.
The BERTScore-P and BERTScore-R should be swapped if you swap the candidates and references because they are asymmetric. 
Alternatively, you can get the scores of all candidates and references and select the best one, our BERTScorer caches duplicated sentences, so it shouldn't be slower if you eval them altogether.
I hope either of them solves your problem.

Best,
Felix

**Closed** 2021-06-15 02:13 UTC
